### PR TITLE
Ics fixes

### PR DESCRIPTION
**Pull request by vduong10**
Pull request for HMIL-7, 9, 10, 11, 14

### CODE REVIEW

**Comment by zeenix** [comment]
Thanks so much @vduong10. On a quick look, looks good but if you could modify the commit logs to adhere to our new (some months old now) rules, that would be greatly appreciated: https://at.projects.genivi.org/wiki/display/PROJ/Rules+for+Commit+Messages

**Comment by vduong10** [comment]
Yes, I will. Thank you for the link!

**Comment by vduong10** [comment]
@zeenix I've reworded the git commit messages according to the link you had sent me. I am not clear on how to update it here.

**Comment by zeenix** [comment]
@vduong10 Cool, as the (easily missable) message above says, you need to push you changes to ics_fixes branch. You'll need to do a forced push `git push -f`.

**Comment by vduong10** [comment]
Got it, thanks!

**Comment by zeenix** [comment]
@vduong10 Hi, how did rebasing go?

**Comment by vduong10** [comment]
@zeenix  ? Can you elaborate? Thanks in advance!

**Comment by zeenix** [comment]
@vduong10 the `git rebase` you needed to do to re-write your commit logs. We really need this merged soon so please let me know if I'm asking for too much. :)

**Comment by vduong10** [comment]
@zeenix I believe it's already done, the re-write was done and i had done a push -f already, so the new commit format should be there.

**Comment by zeenix** [comment]
@vduong10 ah you did that already before you asked how you can update them here. So I got confused. :) I'll test these changes first thing tomorrow and if everything is in order, I'll push.

**Comment by zeenix** [comment]
I merged already to make testing easy. Will report back if there is an issue.

**Pull request merged**
